/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.signer.jwslib;

import org.junit.Test;
import static org.junit.Assert.*;

public class JWTGeneratorTest {
    @Test 
    public void testNullKey() throws Exception {
    	JWTGenerator generator = new JWTGenerator(null, null, "issuer");
    	generator.build("subject");
    }
}
