/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.signer.jwslib;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import java.lang.IllegalArgumentException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;

public class JWTVerifierTest {
	private static RSAPrivateKey privateKey;
	private static RSAPublicKey publicKey;
	
	@BeforeClass
	public static void setUp() throws Exception {
		KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
		kpg.initialize(2048);
		KeyPair kp = kpg.generateKeyPair();
		privateKey = (RSAPrivateKey)kp.getPrivate();
		publicKey = (RSAPublicKey)kp.getPublic();
	}
	
    @Test(expected = IllegalArgumentException.class)
    public void testNullKey() throws Exception {
    	JWTGenerator generator = new JWTGenerator(privateKey, "issuer");
    	String jwt = generator.build("subject");
    	JWTVerifier verifier = new JWTVerifier(null);
    	verifier.verify(jwt);
    }
    
    @Test(expected = BadParamException.class)
    public void testNulToken() throws Exception {
    	JWTVerifier verifier = new JWTVerifier(publicKey);
    	verifier.verify(null);
    }
    
    @Test(expected = IllegalArgumentException.class)
    public void testInvalidToken() throws Exception {
    	JWTVerifier verifier = new JWTVerifier(publicKey);
    	verifier.verify("invalid.token.null");
    }
    
    @Test
    public void testValidJwt() throws Exception {
    	JWTGenerator generator = new JWTGenerator(privateKey, "issuer");
    	String jwt = generator.build("subject");
    	JWTVerifier verifier = new JWTVerifier(publicKey);
    	JWTVerifier.Claims claims = verifier.verify(jwt);
    	Assert.assertEquals("issuer", claims.getIssuer());
    	Assert.assertEquals("subject", claims.getSubject());
    }
}
